CREATE TABLE IF NOT EXISTS project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50),
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    subject VARCHAR(255),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    type VARCHAR(50),
    status VARCHAR(50) NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    token_encoded VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE'
);

CREATE INDEX IF NOT EXISTS idx_message_project_id ON message(project_id);
CREATE INDEX IF NOT EXISTS idx_token_project_id ON token(project_id);
CREATE INDEX IF NOT EXISTS idx_token_encoded ON token(token_encoded);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_project_set_updated_at ON project;
CREATE TRIGGER trg_project_set_updated_at
BEFORE UPDATE ON project
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_message_set_updated_at ON message;
CREATE TRIGGER trg_message_set_updated_at
BEFORE UPDATE ON message
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

INSERT INTO project (id, name, type, description)
VALUES (1, 'Demo Project', 'demo', 'This is a demo project for testing purposes.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO message (project_id, message, subject, name, email, phone, type, ip_address)
SELECT 1, 'This is a test message.', 'Test Subject', 'John Doe', 'john.doe@example.com', '123-456-7890', 'info', '192.168.1.1'
WHERE EXISTS (SELECT 1 FROM project WHERE id = 1)
  AND NOT EXISTS (
      SELECT 1 FROM message WHERE project_id = 1 AND email = 'john.doe@example.com' AND message = 'This is a test message.'
  );
